apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-flip
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0045-tenant/tkwch-fix-0075-0045-app/devfile-sample-flip@sha256:ac4b446dcb78bd108ec8c632fc59754a88728675df09c277f4bfb2ab4d2ce66c
        name: my-nodejs
        resources: {}
status: {}
